#!/bin/zsh

alias py="python"
alias vim="nvim"
alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.config/nvim/init.vim"
alias bspwmrc="vim ~/.config/bspwm/bspwmrc"
alias sxhkdrc="vim ~/.config/sxhkd/sxhkdrc"
alias comptonconfig="vim ~/.config/compton/compton.conf"
alias rm="rm -I"
alias grep="grep --color=auto"
alias removeorphans="sudo pacman -Rns $(pacman -Qtdq)"
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
