#!/bin/sh
#        __                       __
#   ___ / /___ ____ __ ___  ___  / /_
#  (_-</ __/ // /\ \ // _ \/ _ \/ __/
# /___/\__/\_,_//_\_\/_//_/\___/\__/
# https://github.com/stuxnot

###############################
# ### Table of Contents ###
#
# 1. General Configuration
# 2. Desktop Configuration
# 3. Autostart
#
###############################

###############################
#
# General Configuration
#
###############################
bspc config border_width         3
bspc config window_gap           7

bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#2c2826

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

###############################
#
# Desktop Configuration
#
###############################
if [[ -z $SIDE_MONITOR ]]; then
    bspc monitor -d web tmp mp vlt chat mail a b c d
else
    bspc monitor $MONITOR -d a b c d
    bspc monitor $SIDE_MONITOR -d web tmp mp vlt chat mail 
fi

bspc rule -a discord desktop='^5'
bspc rule -a KeePassXC desktop='^4' state=tiled follow=on
bspc rule -a Zathura state=tiled
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Thunderbird desktop='^6' follow=on
bspc rule -a Signal desktop='^5' follow=on
bspc rule -a strawberry desktop='^3' follow=on

[[ -z $(pidof sxhkd) ]] ||  killall sxhkd


###############################
#
# Autostart
#
###############################
HOST=$(cat /etc/hostname)

sxhkd &

[[ -z "$MONITOR" ]] || $HOME/.config/polybar/launch.sh

# Hide the mouse pointer after 5 seconds and ignore small mouse changes.
[[ -z "$(pidof unclutter)" ]] && unclutter -jitter 100 &

## applets ##

[[ -z "$(pidof blueman-applet)" ]] && blueman-applet &

[[ -z "$(pidof pasystray)" ]] && pasystray &


if [[ "$HOST" = "kronos" ]]; then
    [[ -z "$(pidof nm-applet)" ]] && nm-applet &
fi

if [[ "$HOST" = "hyperion" ]]; then
    [[ -z "$(pidof picom)" ]] && picom &

    liquidctl --match nzxt initialize && liquidctl --match nzxt set sync speed 30

    feh --bg-center $HOME/img/wallpaper/planetary_1.png $HOME/img/wallpaper/planetary_2.png
fi

[[ -z "$(pidof keepassxc)" ]] && keepassxc &

# Fix for bspwm + java
wmname LG3D

# Set caps_lock as escape and enable umlaute.
# xmodmap -e 'clear Lock' $HOME/.Xmodmap
