#!/bin/sh
#        __                       __ 
#   ___ / /___ ____ __ ___  ___  / /_
#  (_-</ __/ // /\ \ // _ \/ _ \/ __/
# /___/\__/\_,_//_\_\/_//_/\___/\__/ 
# https://github.com/stuxnot                                   
 
###############################
# ### Table of Contents ###
# 
# 1. General Configuration
# 2. Desktop Configuration
# 3. Autostart
#
###############################

###############################
#
# General Configuration
#
###############################
bspc config border_width         2
bspc config window_gap           0

bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

###############################
#
# Desktop Configuration
#
###############################
if [[ -z $SIDE_MONITOR ]]; then
    bspc monitor -d web a b c mail chat mp vlt 

    bspc rule -a discord desktop='^6'
    # https://github.com/baskerville/bspwm/issues/291
    # works with: https://github.com/dasJ/spotifywm
    bspc rule -a Spotify desktop='^7' state=pseudo_tiled
    bspc rule -a KeePassXC desktop='^8'

    [[ -z $(pidof sxhkd) ]] && sxhkd -c $HOME/.config/sxhkd/laptop &
else
    bspc monitor $MONITOR -d a b c d e
    bspc monitor $SIDE_MONITOR -d web mail chat mp vlt

    bspc rule -a discord desktop='^3'
    bspc rule -a Spotify desktop='^4' state=pseudo_tiled follow=on
    bspc rule -a KeePassXC desktop='^5' state=tiled follow=on

    [[ -z $(pidof sxhkd) ]] && sxhkd -c $HOME/.config/sxhkd/desktop &
fi

bspc rule -a Zathura state=tiled
bspc rule -a firefox desktop='^1' follow=on

###############################
#
# Autostart
#
###############################

if [[ "$HOST" = "kronos" ]]; then
    [[ -z $(pidof nm-applet) ]] && nm-applet & 
fi

# Set caps_lock as escape and enable umlaute.
xmodmap -e 'clear Lock' $HOME/.Xmodmap 

[[ -z $(pidof pasystray) ]] && pasystray &
[[ -z $(pidof unclutter) ]] && unclutter -jitter 100 &

keepassxc &

# Set background via feh
feh --bg-scale $HOME/img/wallpaper/frosted.jpg

[[ -z $MONITOR ]] || $HOME/.config/polybar/launch.sh
