#!/bin/sh
#        __                       __
#   ___ / /___ ____ __ ___  ___  / /_
#  (_-</ __/ // /\ \ // _ \/ _ \/ __/
# /___/\__/\_,_//_\_\/_//_/\___/\__/
# https://github.com/stuxnot

###############################
# ### Table of Contents ###
#
# 1. General Configuration
# 2. Desktop Configuration
# 3. Autostart
#
###############################

###############################
#
# General Configuration
#
###############################
bspc config border_width         3
bspc config window_gap           7

bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#2c2826

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

###############################
#
# Desktop Configuration
#
###############################
if [[ -z $SIDE_MONITOR ]]; then
    bspc monitor -d web tmp mp vlt chat mail a b c d e
else
    bspc monitor $MONITOR -d a b c d e
    bspc monitor $SIDE_MONITOR -d web tmp mp vlt chat mail 
fi

bspc rule -a discord desktop='^5'
bspc rule -a KeePassXC desktop='^4' state=tiled follow=on
bspc rule -a Zathura state=tiled
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Signal desktop='^5' follow=on

[[ -z $(pidof sxhkd) ]] ||  killall sxhkd


###############################
#
# Autostart
#
###############################

sxhkd &

[[ -z "$(pidof picom)" ]] && picom &

[[ -z "$(pidof blueman-applet)" ]] && blueman-applet &

if [[ "$(hostname)" = "kronos" ]]; then
    [[ -z "$(pidof nm-applet)" ]] && nm-applet &
fi

# Set caps_lock as escape and enable umlaute.
# xmodmap -e 'clear Lock' $HOME/.Xmodmap

[[ -z "$(pidof pasystray)" ]] && pasystray &

[[ -z "$(pidof unclutter)" ]] && unclutter -jitter 100 &

[[ -z "$(pidof keepassxc)" ]] && keepassxc &

[[ -z "$(pidof blueman-applet)" ]] && blueman-applet &

# Set background via feh
feh --bg-fill $HOME/img/wallpaper/fox.jpg

[[ -z "$MONITOR" ]] || $HOME/.config/polybar/launch.sh
